language: node_js
node_js:
 - "node"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
codecov:
  token: 032f59ee-4fcd-47e6-8b22-47930fe3e7f2


#language: android 
#jdk: oraclejdk8

#components: 
#  - tools
#  - tools
#  - platform-tools
#  - extra-google-google-play-services
#  - extra

# language: node_js
# node_js: 
# -11.6.0
# cache: yarn

# install: 
#   - yarn install

# script: 
#   - yarn test
#   - yarn run build

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: gh_pages
